---
- hosts: ami_f95ef58a
  remote_user: ubuntu
  tasks:
    - name: check connection
      ping:

- hosts: ami_8b8c57f8
  remote_user: ec2-user
  tasks:
    - name: check connection
      ping:

- hosts: ami_b0ac25c3
  remote_user: ec2-user
  tasks:
    - name: check connection
      ping:

     
