# Sample code from ansible github issue tracker to group machines based on login user names. 
# Does not work because machines are ignored in subsequent plays when connection cannot be established.
---
- hosts: all
  remote_user: ec2-user
  tasks:
    - name: make those that work part of ec2 group
      group_by: key=ec2

- hosts: all
  remote_user: ubuntu
  tasks:
    - name: group by ubuntu user
      group_by: key=ubuntu_os

- hosts: ubuntu_os
  remote_user: ubuntu
  tasks:
    - name: ping test
      ping:

- hosts: ec2
  remote_user: ec2-user
  tasks:
    - name: ping test
      ping:

